M48
; DRILL file {KiCad 9.0.7} date 2026-03-13T12:28:49+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-13T12:28:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C2.700
%
G90
G05
T1
X192.82Y-82.235
X198.6Y-82.235
T2
X215.3Y-85.1
X218.3Y-85.1
T3
X141.8Y-26.2
X149.8Y-26.2
T4
X131.5Y-55.65
X131.6Y-45.65
X138.5Y-55.65
X138.6Y-45.65
T5
X132.9Y-28.0
X132.9Y-84.0
X226.4Y-28.0
X226.4Y-84.0
M30
